### ISSUE TITLE
Private scripts

### ISSUE THREAD

**Issue by Yaya-Cout** [Yaya-Cout/Upsilon-Workshop-API#1]
Adding support for private scripts would be great.
Privates scripts could be shared with some persons or private.

**Comment by BloomyInDev** [comment]
It can be like youtube with Public, Private and Unlisted ?

**Comment by Yaya-Cout** [comment]
It seems to be a good idea.
Unlisted could be used to share scripts privately, but without having the need to manage users to add manually.

**Comment by Yaya-Cout** [comment]
Done in ed074de44fe582fe84befff2e4043cf7948cc644 !
